[package]
name = "vm"
version = "0.1.0"
authors = ["robin <beemo@openmailbox.org>"]
edition = "2018"

[dependencies]
regex = "1.0.5"
lazy_static = "1.1.0"
byteorder = "1"
combine = {path = "../combine"}
clap = "*"